version: "2"
services:

    lb:
      restart: always
      image: dockercloud/haproxy:1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80
      links:
        - nginx
        - php


    nginx:
      restart: always
      image: nginx
      volumes:
        - ./www/frontend/web:/usr/share/nginx/html
        - ./www/backend/web:/usr/share/nginx/html/office
      environment:
        - VIRTUAL_HOST_WEIGHT=2
        - VIRTUAL_HOST=*/assets/*, */office/assets/*


    php:
      restart: always
      build: ./build/php
      volumes:
        - ./www:/var/www/html
      links:
        - mysql
      environment:
        - API_TOKEN=<YOUR GITHUB API TOKEN>
        - VIRTUAL_HOST_WEIGHT=1
        - VIRTUAL_HOST=*
        

    mysql:
      restart: always
      image: mysql
      container_name: mysql
      ports:
        - "3306:3306"
      volumes:
        - ./build/mysql:/docker-entrypoint-initdb.d
        - ./database:/var/lib/mysql:rw
        - ./stack/localdb/:/stack/localdb:rw
      environment:
        - MYSQL_DATABASE=world
        - MYSQL_ROOT_PASSWORD=password
      command: "/stack/localdb/run.sh"


    pma:
      restart: always
      image: phpmyadmin/phpmyadmin
      links:
       - mysql:db
      ports:
        - 8080:80
